### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../FeatGeneration/feature/wv_embedding.pkl'

### ISSUE THREAD

**Issue by Presyt** [Bayi-Hu/Pump-and-Dump-Detection-on-Cryptocurrency#1]
Hello, bro. It seems that a file is missing. Could you fix this problem? thank you so much!

Traceback (most recent call last):
  File "run_train.py", line 237, in <module>
    tf.app.run()
  File "/home/gcc/anaconda3/envs/pump/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/gcc/anaconda3/envs/pump/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gcc/anaconda3/envs/pump/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "run_train.py", line 123, in main
    feat_generator = FeatGenerator(FLAGS.train_input_file, FLAGS.epoch, FLAGS.batch_size)
  File "/home/gcc/Blockchain_System/Model/market_manipulation/Pump-and-Dump-Detection-on-Cryptocurrency/TargetCoinPrediction/SeqModel/data_loader.py", line 26, in __init__
    self.tensor_dict = self.tensor_generation(self.features)
  File "/home/gcc/Blockchain_System/Model/market_manipulation/Pump-and-Dump-Detection-on-Cryptocurrency/TargetCoinPrediction/SeqModel/data_loader.py", line 117, in tensor_generation
    with open("../FeatGeneration/feature/wv_embedding.pkl", "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../FeatGeneration/feature/wv_embedding.pkl'

**Comment by Bayi-Hu** [comment]
Hi, just see the issue. I have uploaded the file "wv_embedding.pkl" to the FeatGeneration/feature/ directory.
